name: Common Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [22.3.2]

    steps:
    - uses: actions/checkout@v2

    - name: Run Collector
      run: docker-compose up -d

    - uses: gleam-lang/setup-erlang@v1.0.0
      with:
        otp-version: ${{ matrix.otp_version }}
    - name: Compile
      run: rebar3 compile
    - name: CT tests
      run: rebar3 ct
    - name: Dialyzer
      run: rebar3 dialyzer
