version: "3"
services:
  otel:
    image: otel/opentelemetry-collector-contrib-dev:954d0bbc8e80c88380a801443940c7c91779f928
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    ports:
      - 55681:55681
      - 4317:4317
    volumes:
      - ./config/otel-collector-config.yaml:/conf/otel-collector-config.yaml
    links:
      - zipkin

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
    privileged: true
