# OpenTelemetry Collector config that receives OTLP and exports to Zipkin
receivers:
  otlp:
    endpoint: "localhost:9090"
processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
exporters:
  zipkin:
    url: "http://localhost:9411/api/v2/spans"
extensions:
  zpages: {}
service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
