name: Elixir

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.0.1'
          elixir-version: '1.12.1'
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            apps/opentelemetry_api/deps
          key: v3-${{ hashFiles('apps/opentelemetry_api/mix.lock') }}
      - run: mix format --check-formatted
      - run: mix deps.get
        working-directory: apps/opentelemetry_api/
      - run: mix format --check-formatted
        working-directory: apps/opentelemetry_api/
  sdk_tests:
    runs-on: ${{ matrix.os }}
    name: Test on Elixir ${{ matrix.elixir_version }} (OTP ${{ matrix.otp_version }}) and ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['24.0.1', '23.3.4.1', '22.3.4.19', '21.3.8.23']
        elixir: ['1.12.1', '1.11.4']
        os: [ubuntu-18.04]
        exclude:
          - otp_version: '21.3.8.23'
            elixir: '1.12.1'
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
      ELIXIR_VERSION: ${{ matrix.elixir }}
      OTEL_TRACES_EXPORTER: "none"
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir }}
      - name: Compile
        run: rebar3 as test compile
      - name: ExUnit
        run: mix test test/otel_tests.exs

  api_tests:
    runs-on: ${{ matrix.os }}
    name: Test on Elixir ${{ matrix.elixir_version }} (OTP ${{ matrix.otp_version }}) and ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['24.0.1', '23.3.4.1', '22.3.4.19', '21.3.8.23']
        elixir: ['1.12.1', '1.11.4']
        os: [ubuntu-18.04]
        exclude:
          - otp_version: '21.3.8.23'
            elixir: '1.12.1'
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
      ELIXIR_VERSION: ${{ matrix.elixir }}
    defaults:
      run:
        working-directory: apps/opentelemetry_api/
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            apps/opentelemetry_api/deps
            apps/opentelemetry_api/_build
          key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.elixir }}-v3-${{ hashFiles(format('{0}{1}', github.workspace, '/apps/opentelemetry_api/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.elixir }}-
      - run: mix deps.get
        name: Deps
      - run: mix test --cover
        name: ExUnit
      - uses: codecov/codecov-action@v1
        if: ${{ always() }}
        with:
          file: apps/opentelemetry_api/coverage.xml
          env_vars: OTP_VERSION,ELIXIR_VERSION
          flags: api,elixir

  dialyze:
    runs-on: ${{ matrix.os }}
    name: Dialyze on Elixir ${{ matrix.elixir_version }} (OTP ${{ matrix.otp_version }}) and ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['24.0.1']
        elixir: ['1.12.1']
        os: [ubuntu-18.04]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
      ELIXIR_VERSION: ${{ matrix.elixir }}
    defaults:
      run:
        working-directory: apps/opentelemetry_api/
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            apps/opentelemetry_api/deps
            apps/opentelemetry_api/_build
          key: ${{ runner.os }}-dialyzer-${{ matrix.otp_version }}-${{ matrix.elixir }}-v3-${{ hashFiles('apps/opentelemetry_api/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.elixir }}-
      - run: mix deps.get
        name: Deps
      - run: mix dialyzer
        name: Dialyzer
