name: Common Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    services:
      zipkin:
        image: openzipkin/zipkin-slim
        ports:
        - 9411:9411
      otelcol:
        image: otel/opentelemetry-collector-dev
        ports:
        - 9090:9090
        volumes:
        - ./config/otel-collector-config.yaml:/conf/otel-collector-config.yaml

    strategy:
      matrix:
        otp_version: [22]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: rebar3 compile
    - name: CT tests
      run: rebar3 ct
    - name: Dialyzer
      run: rebar3 dialyzer
